apiVersion: v1
kind: Service
metadata:
  name: flask-hello
  namespace: hello
spec:
  selector:
    app: flask-hello
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: hello
spec:
  selector:
    matchLabels:
      app: flask-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask-hello
        image: ilovefran/flask-hello:1.0
        ports:
        - containerPort: 8080